route:
  group_by: [Alertname]
  # Send all notifications to email.
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: a@gmail.com
    from: a0@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: "a0@gmail.com"
    auth_identity: "a0@gmail.com"
    auth_password: "secret"
